package co.assip.erp.cartera.analisis.garantiascobertura;
import co.assip.erp.cartera.analisis.garantiascobertura.dto.*;
import lombok.RequiredArgsConstructor;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;
import java.sql.*;
import java.time.LocalDate;
import java.util.*;
@Repository @RequiredArgsConstructor
public class GarantiasCoberturaRepository {
 private final JdbcTemplate jdbc;
 public List<LocalDate> listarCortes(){return jdbc.query("SELECT DISTINCT fecha_corte FROM cartera.vw_garantias_cobertura_resumen ORDER BY fecha_corte DESC",(r,n)->r.getObject("fecha_corte",LocalDate.class));}
 public Optional<GarantiasCoberturaResumenDTO> obtenerResumen(LocalDate f){return jdbc.query("SELECT * FROM cartera.vw_garantias_cobertura_resumen WHERE fecha_corte = ?",this::mapResumen,f).stream().findFirst();}
 public List<GarantiasCoberturaBienDTO> listarBienes(LocalDate f){return jdbc.query("SELECT * FROM cartera.vw_garantias_cobertura_bienes WHERE fecha_corte = ? ORDER BY CASE WHEN estado_cobertura='INSUFICIENTE' THEN 0 ELSE 1 END, deficit_cobertura DESC, saldo_total_creditos_bien DESC, id_bien",this::mapBien,f);}
 public List<GarantiasCoberturaBienDTO> listarBienesInsuficientes(LocalDate f){return jdbc.query("SELECT * FROM cartera.vw_garantias_cobertura_bienes WHERE fecha_corte=? AND estado_cobertura='INSUFICIENTE' ORDER BY deficit_cobertura DESC,id_bien",this::mapBien,f);}
 public List<GarantiasCoberturaCreditoDTO> listarCreditos(LocalDate f){return jdbc.query("SELECT * FROM cartera.vw_garantias_cobertura_creditos WHERE fecha_corte=? ORDER BY CASE WHEN estado_cobertura_credito='INSUFICIENTE' THEN 0 ELSE 1 END, exposicion_no_cubierta DESC,saldo_credito DESC,id_cartera_credito",this::mapCredito,f);}
 public List<GarantiasCoberturaCreditoDTO> listarCreditosInsuficientes(LocalDate f){return jdbc.query("SELECT * FROM cartera.vw_garantias_cobertura_creditos WHERE fecha_corte=? AND estado_cobertura_credito='INSUFICIENTE' ORDER BY exposicion_no_cubierta DESC,id_cartera_credito",this::mapCredito,f);}
 public List<GarantiasCoberturaDetalleDTO> listarDetalle(LocalDate f){return jdbc.query("SELECT * FROM cartera.vw_garantias_cobertura_detalle WHERE fecha_corte=? ORDER BY CASE WHEN estado_cobertura='INSUFICIENTE' THEN 0 ELSE 1 END,deficit_cobertura DESC,id_bien,saldo_credito DESC,id_cartera_credito",this::mapDetalle,f);}
 public List<GarantiasCoberturaDetalleDTO> listarDetallePorBien(LocalDate f,Long id){return jdbc.query("SELECT * FROM cartera.vw_garantias_cobertura_detalle WHERE fecha_corte=? AND id_bien=? ORDER BY saldo_credito DESC,id_cartera_credito",this::mapDetalle,f,id);}
 public List<GarantiasCoberturaDetalleDTO> listarDetallePorCredito(LocalDate f,Long id){return jdbc.query("SELECT * FROM cartera.vw_garantias_cobertura_detalle WHERE fecha_corte=? AND id_cartera_credito=? ORDER BY id_bien",this::mapDetalle,f,id);}
 private GarantiasCoberturaResumenDTO mapResumen(ResultSet r,int n)throws SQLException{return new GarantiasCoberturaResumenDTO(i(r,"id_cierre_cartera"),r.getObject("fecha_corte",LocalDate.class),l(r,"cantidad_bienes"),r.getBigDecimal("valor_total_bienes"),l(r,"bienes_suficientes"),l(r,"bienes_insuficientes"),r.getBigDecimal("margen_total_bienes"),r.getBigDecimal("deficit_total_bienes"),l(r,"cantidad_creditos_con_bien"),l(r,"creditos_con_multiples_bienes"),r.getBigDecimal("saldo_creditos_con_bien"),r.getBigDecimal("valor_garantias_asignadas"),r.getBigDecimal("cobertura_efectiva_creditos"),r.getBigDecimal("exposicion_no_cubierta"),l(r,"creditos_cobertura_suficiente"),l(r,"creditos_cobertura_insuficiente"),r.getBigDecimal("porcentaje_cobertura_efectiva"),r.getBigDecimal("porcentaje_exposicion_no_cubierta"));}
 private GarantiasCoberturaBienDTO mapBien(ResultSet r,int n)throws SQLException{return new GarantiasCoberturaBienDTO(i(r,"id_cierre_cartera"),r.getObject("fecha_corte",LocalDate.class),l(r,"id_bien"),r.getString("tipo_bien"),r.getString("descripcion_bien"),r.getString("identificacion_bien"),r.getBigDecimal("valor_bien_fecha_corte"),l(r,"cantidad_creditos_bien"),r.getBigDecimal("saldo_total_creditos_bien"),r.getBigDecimal("valor_garantia_distribuida"),r.getBigDecimal("cobertura_efectiva_bien"),r.getBigDecimal("porcentaje_cobertura_bien"),r.getBigDecimal("margen_cobertura"),r.getBigDecimal("deficit_cobertura"),r.getString("estado_cobertura"));}
 private GarantiasCoberturaCreditoDTO mapCredito(ResultSet r,int n)throws SQLException{return new GarantiasCoberturaCreditoDTO(i(r,"id_cierre_cartera"),r.getObject("fecha_corte",LocalDate.class),l(r,"id_cartera_credito"),l(r,"id_datos_personal"),r.getString("tipo_documento"),r.getString("documento"),r.getString("nombre_completo"),r.getString("pagare_cartera"),i(r,"id_agencia"),l(r,"id_linea_credito"),r.getString("codigo_linea_credito"),r.getString("nombre_linea_credito"),r.getBigDecimal("saldo_credito"),l(r,"cantidad_bienes"),r.getBigDecimal("valor_garantias_asignadas"),r.getBigDecimal("cobertura_efectiva_credito"),r.getBigDecimal("exposicion_no_cubierta"),r.getBigDecimal("porcentaje_cobertura_credito"),r.getString("estado_cobertura_credito"),i(r,"dias_mora"),r.getString("edad_contable_resultado"),r.getBigDecimal("deterioro_capital"),r.getBigDecimal("deterioro_intereses"),r.getBigDecimal("deterioro_otros"),r.getBigDecimal("deterioro_total"),l(r,"cantidad_codeudores_actual"),r.getBoolean("tiene_codeudor_actual"));}
 private GarantiasCoberturaDetalleDTO mapDetalle(ResultSet r,int n)throws SQLException{return new GarantiasCoberturaDetalleDTO(i(r,"id_cierre_cartera"),r.getObject("fecha_corte",LocalDate.class),l(r,"id_bien"),r.getString("tipo_bien"),r.getString("descripcion_bien"),r.getString("identificacion_bien"),r.getBigDecimal("valor_bien_fecha_corte"),l(r,"cantidad_creditos_bien"),r.getBigDecimal("saldo_total_creditos_bien"),r.getBigDecimal("cobertura_efectiva_bien"),r.getBigDecimal("porcentaje_cobertura_bien"),r.getBigDecimal("margen_cobertura"),r.getBigDecimal("deficit_cobertura"),r.getString("estado_cobertura"),i(r,"id_cierre_cartera_credito"),l(r,"id_cartera_credito"),l(r,"id_datos_personal"),r.getString("tipo_documento"),r.getString("documento"),r.getString("nombre_completo"),r.getString("pagare_cartera"),i(r,"id_agencia"),l(r,"id_linea_credito"),r.getString("codigo_linea_credito"),r.getString("nombre_linea_credito"),r.getString("codigo_clasificacion_credito"),r.getString("descripcion_clasificacion_credito"),r.getString("codigo_garantia_credito"),r.getString("descripcion_garantia_credito"),r.getString("codigo_destino_economico"),r.getString("descripcion_destino_economico"),r.getBigDecimal("saldo_credito"),r.getBigDecimal("porcentaje_credito_bien"),r.getBigDecimal("valor_garantia_credito_bien"),i(r,"dias_mora"),r.getString("edad_contable_resultado"),r.getBigDecimal("deterioro_capital"),r.getBigDecimal("deterioro_intereses"),r.getBigDecimal("deterioro_otros"),r.getBigDecimal("deterioro_total"),l(r,"cantidad_codeudores_actual"),r.getBoolean("tiene_codeudor_actual"),r.getString("alerta_cobertura"));}
 private Long l(ResultSet r,String c)throws SQLException{long v=r.getLong(c);return r.wasNull()?null:v;} private Integer i(ResultSet r,String c)throws SQLException{int v=r.getInt(c);return r.wasNull()?null:v;}
}
