export interface ConcentracionControl { primerCorteDisponible:string; ultimoCorteDisponible:string; corteSugerido:string; }
export interface ConcentracionResumen {
  fechaCorte:string; cantidadCreditos:number; cantidadDeudores:number; saldoTotal:number; deterioroTotal:number;
  saldoMayorDeudor:number; porcentajeMayorDeudor:number; saldoTop10:number; porcentajeTop10:number; saldoTop20:number; porcentajeTop20:number;
  saldoTop50:number; porcentajeTop50:number; hhi10000:number; deudoresPara50Pct:number; deudoresPara80Pct:number;
  porcentajeDeudoresPara50Pct:number; porcentajeDeudoresPara80Pct:number; deudoresConDeterioro:number;
  deterioroMayorDeudor:number; porcentajeDeterioroMayorDeudor:number; deterioroTop10:number; porcentajeDeterioroTop10:number;
  deterioroTop20:number; porcentajeDeterioroTop20:number; deterioroTop50:number; porcentajeDeterioroTop50:number;
}
export interface ConcentracionSegmento { idSegmento:number|null; codigo:string; descripcion:string; cantidadCreditos:number; cantidadDeudores:number; saldo:number; porcentajeCartera:number; deterioro:number; porcentajeDeterioro:number; brechaDeterioro:number; saldoPromedio:number; mayorCredito:number; }
export interface ConcentracionRanking { posicion:number; idDatosPersonal:number; documento:string; nombreCompleto:string; cantidadCreditos:number; saldo:number; porcentajeCartera:number; porcentajeCarteraAcumulado:number; deterioro:number; porcentajeDeterioro:number; porcentajeDeterioroAcumulado:number; }
export interface ConcentracionDeudor { posicion:number; idDatosPersonal:number; documento:string; nombreCompleto:string; cantidadCreditos:number; saldo:number; porcentajeCartera:number; porcentajeAcumulado:number; deterioro:number; porcentajeDeterioro:number; agencias:string; lineas:string; mayorEdadContable:string; diasMoraMaximos:number; telefono:string|null; celular:string|null; correo:string|null; }
export interface ConcentracionCredito { idCarteraCredito:number; idDatosPersonal:number; documento:string; nombreCompleto:string; pagareCartera:string; idAgencia:number; codigoAgencia:string; nombreAgencia:string; idLineaCredito:number; codigoLineaCredito:string; nombreLineaCredito:string; codigoClasificacionCredito:string; descripcionClasificacionCredito:string; codigoGarantiaCredito:string; descripcionGarantiaCredito:string; tipoGarantia:string; codigoSubgarantia:string; descripcionSubgarantia:string; codigoDestinoEconomico:string; descripcionDestinoEconomico:string; fechaDesembolso:string; saldo:number; porcentajeCartera:number; edadContable:string; diasMora:number; deterioroCapital:number; deterioroIntereses:number; deterioroOtros:number; deterioroTotal:number; perdidaEsperada:number; cantidadBienesGarantia:number; valorGarantiasTotal:number; porcentajeGarantiasCredito:number; valorGarantiasCredito:number; valorFondosGarantias:number; }
export interface ConcentracionFiltros { fechaCorte:string; idAgencia:number|null; idLineaCredito:number|null; codigoGarantia:string; codigoClasificacion:string; edadContable:string; codigoDestino:string; }
