spring:
  application:
    name: assip-erp-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/assip_erp
    username: postgres
    password: Cagope1234+
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    create-schemas: true
    baseline-on-migrate: true
    validate-on-migrate: true
    group: true

    # 📁 Ruta única para que lea todas las migraciones
    locations: classpath:db/migration

    # 🧩 Esquemas manejados en orden
    default-schema: seguridad
    schemas: seguridad, catalogos, general, hoja_vida

    # 🏷️ Control de versión dentro del esquema seguridad
    table: flyway_schema_history

    # 🪶 Log de diagnóstico extendido
    placeholders:
      app_user: postgres

server:
  port: 8080
  servlet:
    context-path: /api/v1

logging:
  level:
    root: info
    org.hibernate.SQL: off
    org.hibernate.type.descriptor.sql: off
    org.hibernate.orm.jdbc.bind: off
    org.springframework.orm.jpa: warn
    org.springframework.jdbc.core: warn
    org.flywaydb.core.internal.command: debug   # 🔍 muestra detalle de migraciones
    org.flywaydb.core.internal.sqlscript: debug
