export interface CancelacionPrepagoControl {
  proceso: string;
  estado: string;
  soloLectura: boolean;
}

export interface CancelacionPrepagoResumen {
  idCierreCartera: number;
  fechaCorte: string;
  fechaCorteSiguiente: string;
  creditosExpuestos: number;
  personasExpuestas: number;
  permanencias: number;
  ausenciasTemporales: number;
  prepagos: number;
  cancelacionesNormales: number;
  cancelacionesPosteriores: number;
  salidasDefinitivas: number;
  tasaPermanencia: number;
  tasaSalidaDefinitiva: number;
  tasaPrepagoPoblacion: number;
  participacionPrepagoCancelaciones: number;
  saldoExpuesto: number;
  saldoPrevioPrepagos: number;
  saldoPrevioSalidasDefinitivas: number;
  velocidadAmortizacionPromedio: number;
  medianaVelocidadAmortizacion: number;
  amortizacionesAceleradas: number;
  aumentosSaldo: number;
  porcentajeAmortizacionAcelerada: number;
  vidaContractualPromedioDias: number;
  vidaEfectivaPromedioDias: number;
  porcentajeVidaConsumidaPromedio: number;
  anticipacionPromedioPrepagoDias: number;
  prepagos3190Dias: number;
  prepagos36Meses: number;
  prepagos612Meses: number;
  prepagos12Anios: number;
  prepagos25Anios: number;
  prepagosMas5Anios: number;
}

export interface CancelacionPrepagoLinea {
  idCierreCartera: number;
  fechaCorte: string;
  fechaCorteSiguiente: string;
  idLineaCredito: number;
  codigoLineaCredito: string;
  nombreLineaCredito: string;
  creditosExpuestos: number;
  permanencias: number;
  ausenciasTemporales: number;
  prepagos: number;
  cancelacionesNormales: number;
  cancelacionesPosteriores: number;
  salidasDefinitivas: number;
  tasaPermanencia: number;
  tasaSalidaDefinitiva: number;
  tasaPrepagoPoblacion: number;
  participacionPrepagoCancelaciones: number;
  saldoExpuesto: number;
  saldoPrevioPrepagos: number;
  saldoPrevioSalidasDefinitivas: number;
  velocidadAmortizacionPromedio: number;
  medianaVelocidadAmortizacion: number;
  amortizacionesAceleradas: number;
  aumentosSaldo: number;
  porcentajeAmortizacionAcelerada: number;
  vidaContractualPromedioDias: number;
  vidaEfectivaPromedioDias: number;
  porcentajeVidaConsumidaPromedio: number;
  anticipacionPromedioPrepagoDias: number;
}

export interface CancelacionPrepagoDetalle {
  idCierreCartera: number;
  fechaCorte: string;
  fechaCorteSiguiente: string;
  idCierreCarteraCredito: number;
  idCierreCarteraSiguiente: number | null;
  idCierreCarteraCreditoSiguiente: number | null;
  idCarteraCredito: number;
  idAgencia: number;
  idLineaCredito: number;
  codigoLineaCredito: string;
  nombreLineaCredito: string;
  pagareCartera: string;
  idDatosPersonal: number;
  tipoDocumento: string;
  documento: string;
  nombreCompleto: string;
  codigoClasificacionCredito: string;
  descripcionClasificacionCredito: string;
  codigoDestinoEconomico: string;
  descripcionDestinoEconomico: string;
  valorInicialCredito: number;
  valorDesembolsado: number;
  fechaDesembolso: string;
  fechaFinal: string;
  plazo: number;
  codigoFormaPago: string;
  codigoTipoCuota: string;
  amortizacionCapital: number;
  valorCuota: number;
  alturaCuota: number;
  saldoCorteAnterior: number;
  saldoCorteSiguiente: number | null;
  reduccionSaldo: number | null;
  porcentajeReduccionSaldo: number | null;
  medianaReduccionLinea: number | null;
  percentil75ReduccionLinea: number | null;
  comportamientoAmortizacion: string | null;
  permanece: boolean;
  ausenciaTemporal: boolean;
  salidaDefinitiva: boolean;
  ultimaFechaAparicion: string;
  diasAnticipacion: number | null;
  diasVidaContractual: number | null;
  diasVidaEfectiva: number | null;
  porcentajeVidaConsumida: number | null;
  clasificacionSalida: string;
  rangoAnticipacion: string | null;
  diasMora: number;
  edadContableResultado: string;
  codigoEstadoCartera: string;
  descripcionEstadoCartera: string;
  deterioroCapital: number;
  deterioroIntereses: number;
  deterioroOtros: number;
  deterioroTotal: number;
}

export interface CancelacionPrepagoCredito {
  idCarteraCredito: number;
  idAgencia: number;
  idLineaCredito: number;
  codigoLineaCredito: string;
  nombreLineaCredito: string;
  pagareCartera: string;
  idDatosPersonal: number;
  tipoDocumento: string;
  documento: string;
  nombreCompleto: string;
  codigoClasificacionCredito: string;
  descripcionClasificacionCredito: string;
  codigoDestinoEconomico: string;
  descripcionDestinoEconomico: string;
  valorInicialCredito: number;
  valorDesembolsado: number;
  fechaDesembolso: string;
  fechaFinal: string;
  plazo: number;
  codigoFormaPago: string;
  codigoTipoCuota: string;
  amortizacionCapital: number;
  valorCuota: number;
  primerCorteObservado: string;
  ultimoCorteEvaluable: string;
  cantidadTransiciones: number;
  cantidadPermanencias: number;
  cantidadAusenciasTemporales: number;
  periodosAmortizacionAcelerada: number;
  periodosAumentoSaldo: number;
  velocidadAmortizacionPromedio: number;
  maximaReduccionPorcentual: number;
  ultimoCorteTransicion: string;
  fechaCorteSiguiente: string;
  saldoCorteAnterior: number;
  saldoCorteSiguiente: number | null;
  reduccionSaldo: number | null;
  porcentajeReduccionSaldo: number | null;
  medianaReduccionLinea: number | null;
  percentil75ReduccionLinea: number | null;
  comportamientoAmortizacion: string | null;
  ultimaFechaAparicion: string;
  diasAnticipacion: number | null;
  diasVidaContractual: number | null;
  diasVidaEfectiva: number | null;
  porcentajeVidaConsumida: number | null;
  clasificacionSalida: string;
  rangoAnticipacion: string | null;
  diasMora: number;
  edadContableResultado: string;
  deterioroCapital: number;
  deterioroIntereses: number;
  deterioroOtros: number;
  deterioroTotal: number;
}
